steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/mlops-sentiment-analysis-gcp/mlops-sentiment-analysis-image:v1','.']

- name: 'gcr.io/cloud-builders/docker' 
  args: ['push','gcr.io/mlops-sentiment-analysis-gcp/mlops-sentiment-analysis-image:v1']

