steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/mlops-sentiment-analysis/mlops-sentiment-analysis-image','.']

- name: 'gcr.io/cloud-builders/docker' 
  args: ['push','gcr.io/mlops-sentiment-analysis/mlops-sentiment-analysis-image']