steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/mlops-sentiment-analysis/mlops-sentiment-analysis-image:latest','.']
  options:
  machineType: 'E2_HIGHCPU_8'

- name: 'gcr.io/cloud-builders/docker' 
  args: ['push','gcr.io/mlops-sentiment-analysis/mlops-sentiment-analysis-image:latest']
  options:
  machineType: 'E2_HIGHCPU_8'