steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','europe-docker.pkg.dev/mlops-sentiment-analysis-gcp/eu.gcr.io','.']
  #args: ['build','-t','gcr.io/mlops-sentiment-analysis-gcp/myimage','.']

- name: 'gcr.io/cloud-builders/docker' 
  args: ['push','europe-docker.pkg.dev/mlops-sentiment-analysis-gcp/eu.gcr.io']
  #args: ['push','gcr.io/mlops-sentiment-analysis-gcp/myimage']
