wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.23.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1667662454.825994
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.13.5
      6: 4.23.1
      8:
      - 4
      - 5
method:
  desc: null
  value: bayes
metric:
  desc: null
  value:
    goal: minimize
    name: val_loss
parameters:
  desc: null
  value:
    dropout:
      values:
      - 0.2
      - 0.3
      - 0.4
    lr:
      max: 0.0001
      min: 1.0e-06
    optimizer:
      values:
      - adam
      - sgd
program:
  desc: null
  value: train.py
