wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.23.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1667640014.203093
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      6: 4.23.1
      8:
      - 4
      - 5
dropout:
  desc: null
  value: 0.2
lr:
  desc: null
  value: 1.0e-05
