name: "Run isort"

on:
  push:
    branches: [ master, main, mads ]
  pull_request:
    branches: [ master, main, mads ]
  
jobs:
  build:
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    - name: Lint with flake8
      run: |
        pip install isort
        isort .
      continue-on-error: true