name: "Run isort"

on:
  push:
    branches: [ master, main, mads ]
  pull_request:
    branches: [ master, main, mads ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: jamescurtin/isort-action@master
        with:
            requirementsFiles: "requirements.txt"